#!/usr/bin/env python3
"""
=============================================================================
Secure Customer Service Agent - Deployment Script
=============================================================================
Deploys the agent to Vertex AI Agent Engine with Agent Identity enabled.

This script uses a TWO-STEP approach to enable Agent Identity:
1. Create an empty Agent Engine instance with Agent Identity via Python SDK
2. Deploy code to it via ADK CLI (which properly packages local code)

This workaround is needed because:
- ADK CLI doesn't support identity_type flag
- Python SDK can't properly serialize local code (pickle issues)
- But we can create an empty instance with identity, then update it with code

Usage:
    python deploy.py

After deployment, save the output values to set_env.sh and configure IAM.
=============================================================================
"""

import os
import sys
import subprocess

# =============================================================================
# Configuration
# =============================================================================

PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT") or os.environ.get("PROJECT_ID")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION") or os.environ.get("LOCATION", "us-central1")
STAGING_BUCKET = os.environ.get("STAGING_BUCKET", "").replace("gs://", "")
TEMPLATE_NAME = os.environ.get("TEMPLATE_NAME")
AGENT_ENGINE_ID = os.environ.get("AGENT_ENGINE_ID")  # For updates

# Will be set during deployment
agent_identity = None
effective_identity = None  # From API response, used to construct agent_identity

# Validate
print("=" * 70)
print("   Secure Customer Service Agent - Deployment")
print("=" * 70)
print()

print("Phase 1: Validating Environment")

errors = []
if not PROJECT_ID:
    errors.append("PROJECT_ID not set")
if not LOCATION:
    errors.append("LOCATION not set")
if not STAGING_BUCKET:
    STAGING_BUCKET = f"secure-cs-agent-staging-{PROJECT_ID}"
    print(f"   ⚠️  Using default staging bucket: gs://{STAGING_BUCKET}")
if not TEMPLATE_NAME:
    errors.append("TEMPLATE_NAME not set (run python setup/create_template.py first)")

if errors:
    print("   ❌ Environment validation failed:")
    for error in errors:
        print(f"      - {error}")
    print()
    print("   Run: source set_env.sh")
    sys.exit(1)

print(f"   ✓ PROJECT_ID: {PROJECT_ID}")
print(f"   ✓ LOCATION: {LOCATION}")
print(f"   ✓ AGENT_ENGINE_ID: {AGENT_ENGINE_ID}")
print(f"   ✓ STAGING_BUCKET: gs://{STAGING_BUCKET}")
print(f"   ✓ TEMPLATE_NAME: {TEMPLATE_NAME}")
print()

# =============================================================================
# Create .env file for Agent Engine runtime
# =============================================================================

print("Phase 2: Creating Runtime Environment Configuration")

# Create .env file in agent directory with required variables
agent_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "agent")
env_file_path = os.path.join(agent_dir, ".env")

env_content = f"""# Runtime environment variables for Agent Engine
# Auto-generated by deploy.py

GOOGLE_CLOUD_PROJECT={PROJECT_ID}
GOOGLE_CLOUD_LOCATION={LOCATION}
TEMPLATE_NAME={TEMPLATE_NAME}
GOOGLE_API_PREVENT_AGENT_TOKEN_SHARING_FOR_GCP_SERVICES=False
GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY=True
OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=True
"""

with open(env_file_path, "w") as f:
    f.write(env_content)

print(f"   ✓ Created {env_file_path}")
print(f"   ✓ GOOGLE_CLOUD_PROJECT={PROJECT_ID}")
print(f"   ✓ GOOGLE_CLOUD_LOCATION={LOCATION}")
print(f"   ✓ TEMPLATE_NAME={TEMPLATE_NAME[:50]}...")
print()

# =============================================================================
# Create Agent Engine with Agent Identity (if needed)
# =============================================================================

agent_engine_id = AGENT_ENGINE_ID

if not agent_engine_id:
    print("Phase 3: Creating Agent Engine with Agent Identity")
    print("   Using Python SDK with v1beta1 API to provision Agent Identity...")
    print()

    try:
        import vertexai
        from vertexai import types
        import threading
        import time

        # Create client with v1beta1 API for Agent Identity support
        client = vertexai.Client(
            project=PROJECT_ID,
            location=LOCATION,
            http_options=dict(api_version="v1beta1")
        )

        # Create empty Agent Engine with Agent Identity (no code yet)
        print("   → Creating empty Agent Engine with Agent Identity...")
        print("   ⏳ This typically takes 3-5 minutes (can take up to 15 minutes).")
        print()

        # Progress indicator in background thread
        stop_spinner = threading.Event()
        start_time = time.time()


        def show_progress():
            spinner_chars = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
            idx = 0
            last_update = 0
            while not stop_spinner.is_set():
                elapsed = int(time.time() - start_time)
                mins, secs = divmod(elapsed, 60)

                # Print spinner with elapsed time
                sys.stdout.write(f"\r   {spinner_chars[idx]} Waiting... {mins}m {secs}s elapsed")
                sys.stdout.flush()

                # Every 60 seconds, print a status line
                if elapsed > 0 and elapsed % 60 == 0 and elapsed != last_update:
                    last_update = elapsed
                    sys.stdout.write(f"\r   ℹ️  Still creating Agent Engine... {mins}m elapsed. This is normal.\n")
                    sys.stdout.flush()

                idx = (idx + 1) % len(spinner_chars)
                time.sleep(0.1)

            # Clear the spinner line
            sys.stdout.write("\r" + " " * 60 + "\r")
            sys.stdout.flush()


        # Start progress thread
        progress_thread = threading.Thread(target=show_progress, daemon=True)
        progress_thread.start()

        try:
            remote_app = client.agent_engines.create(
                config={
                    "identity_type": types.IdentityType.AGENT_IDENTITY,
                    "display_name": "Secure Customer Service Agent"
                }
            )
        finally:
            # Stop the spinner
            stop_spinner.set()
            progress_thread.join(timeout=1)

        elapsed_total = int(time.time() - start_time)
        mins, secs = divmod(elapsed_total, 60)

        # Extract the agent engine ID from the response
        # The SDK returns an AgentEngine wrapper - access api_resource.name
        agent_engine_id = None
        effective_identity = None

        try:
            # New SDK structure: remote_app.api_resource.name
            if hasattr(remote_app, 'api_resource') and hasattr(remote_app.api_resource, 'name'):
                resource_name = remote_app.api_resource.name
                agent_engine_id = resource_name.split("/")[-1]

                # Also get the effective_identity if available
                if hasattr(remote_app.api_resource, 'spec') and hasattr(remote_app.api_resource.spec,
                                                                        'effective_identity'):
                    effective_identity = remote_app.api_resource.spec.effective_identity

            # Fallback: try direct .name attribute (older SDK versions)
            elif hasattr(remote_app, 'name'):
                agent_engine_id = remote_app.name.split("/")[-1]

        except Exception as extract_err:
            print(f"   ⚠️  Error extracting ID: {extract_err}")

        if not agent_engine_id:
            print("   ❌ Could not extract Agent Engine ID from response")
            print("   Check the Google Cloud Console for the created agent")
            sys.exit(1)

        print(f"   ✓ Created Agent Engine with Agent Identity: {agent_engine_id}")
        if effective_identity:
            print(f"   ✓ Effective Identity: {effective_identity}")
        print(f"   ✓ Creation took {mins}m {secs}s")
        print()

    except ImportError:
        print("   ❌ Error: google-cloud-aiplatform not installed")
        print("   Run: pip install 'google-cloud-aiplatform[adk,agent_engines]'")
        sys.exit(1)
    except Exception as e:
        print(f"   ❌ Failed to create Agent Engine: {e}")
        print()
        print("   Troubleshooting:")
        print("   - Check API is enabled: gcloud services enable aiplatform.googleapis.com")
        print("   - Verify permissions on the project")
        sys.exit(1)
else:
    print(f"Phase 3: Using Existing Agent Engine: {agent_engine_id}")
    print()

# =============================================================================
# Grant Baseline IAM Permissions to Agent Identity
# =============================================================================

print("Phase 4: Configuring Agent Identity IAM Permissions")
print("   Granting baseline permissions required for agent to start...")
print()

# First, try to use the effective_identity from API response
# Otherwise fall back to constructing it
try:
    if effective_identity:
        # The API returns the identity without the "principal://" prefix
        # Add it if not present
        if effective_identity.startswith("principal://"):
            agent_identity = effective_identity
        else:
            agent_identity = f"principal://{effective_identity}"
    else:
        # Fallback: construct the identity ourselves
        # Get organization ID
        result = subprocess.run(
            ["gcloud", "organizations", "list", "--format=value(ID)", "--limit=1"],
            capture_output=True, text=True, timeout=30
        )
        org_id = result.stdout.strip()

        # Get project number
        result = subprocess.run(
            ["gcloud", "projects", "describe", PROJECT_ID, "--format=value(projectNumber)"],
            capture_output=True, text=True, timeout=30
        )
        
        project_number = result.stdout.strip()
        print(f"Project id for agent identity IAM binding: {project_number}")

        if org_id:
            agent_identity = f"principal://agents.global.org-{org_id}.system.id.goog/resources/aiplatform/projects/{project_number}/locations/{LOCATION}/reasoningEngines/{agent_engine_id}"
        else:
            # No organization - try proj- first (observed in recent API responses)
            agent_identity = f"principal://agents.global.proj-{project_number}.system.id.goog/resources/aiplatform/projects/{project_number}/locations/{LOCATION}/reasoningEngines/{agent_engine_id}"

    print(f"   Agent Identity: {agent_identity}")
    print()

    # Required baseline roles for Agent Identity
    baseline_roles = [
        ("roles/serviceusage.serviceUsageConsumer", "Service Usage Consumer (required for agent startup)"),
        ("roles/aiplatform.user", "AI Platform User (for Vertex AI services, including Sessions)"), # added this line.
        ("roles/aiplatform.expressUser", "AI Platform Express User (required for inference)"),
        ("roles/browser", "Browser (required for project metadata access)"),
        ("roles/bigquery.dataViewer", "BigQuery data viewer role (required for viewing BQ tables)"), #this needs to be added, missing in the codelab.
        ("roles/modelarmor.user", "Model Armor User (required for input/output sanitization)"),
        ("roles/mcp.toolUser", "MCP Tool User (required for OneMCP BigQuery access)"),
        ("roles/bigquery.jobUser", "BigQuery Job User (required for running queries)"),
    ]

    # Track if we need to try alternate format
    tried_alternate = False

    for role, description in baseline_roles:
        print(f"   → Granting {description}...")

        grant_cmd = [
            "gcloud", "projects", "add-iam-policy-binding", PROJECT_ID,
            f"--member={agent_identity}",
            f"--role={role}",
            "--condition=None"
        ]

        print(f" Executing iam policy binding: {' '.join(grant_cmd)}")

        result = subprocess.run(
            grant_cmd,
            capture_output=True,
            text=True,
            timeout=90
        )

        if result.returncode != 0:
            error_msg = result.stderr.strip()

            # If "unknown type" error and we haven't tried alternate format yet
            if "unknown type" in error_msg.lower() and not tried_alternate and "proj-" in agent_identity:
                print(f"   ⚠️  proj- format failed, trying project- format...")
                # Switch to project- format
                agent_identity = agent_identity.replace("agents.global.proj-", "agents.global.project-")
                tried_alternate = True

                # Retry with new format
                grant_cmd[3] = f"--member={agent_identity}"
                result = subprocess.run(grant_cmd, capture_output=True, text=True, timeout=60)

                if result.returncode == 0:
                    print(f"   ✓ Granted {role} (using project- format)")
                    continue

            print(f"   ⚠️  Warning: Could not grant {role}")
            print(f"      Error: {error_msg}")
            print(f"      You may need to grant this manually:")
            print(f"      gcloud projects add-iam-policy-binding {PROJECT_ID} \\")
            print(f'        --member="{agent_identity}" \\')
            print(f"        --role={role}")
        else:
            print(f"   ✓ Granted {role}")

    print()
    print("   ⏳ Waiting 90 seconds for IAM propagation...")
    import time

    time.sleep(90)
    print("   ✓ IAM permissions configured")
    print()

except Exception as e:
    print(f"   ⚠️  Warning: Could not configure IAM automatically: {e}")
    print("   You may need to grant permissions manually before the agent can start.")
    print()
    agent_identity = None

# =============================================================================
# Deploy code using ADK CLI
# =============================================================================

print("Phase 5: Deploying Agent Code")
print("   Using ADK CLI for proper code packaging...")
print()

# Build the adk deploy command
cmd = [
    "adk", "deploy", "agent_engine",
    "--project", PROJECT_ID,
    "--region", LOCATION,
    "--otel_to_cloud",
    "--agent_engine_id", agent_engine_id,
     "agent"
]

print(f"   → Deploying code to Agent Engine: {agent_engine_id}")
print(f"   Command: {' '.join(cmd)}")
print()
print("   (This may take several minutes)")
print()

# Run the deployment
try:
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=os.path.dirname(os.path.abspath(__file__))
    )

    # Print output
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)

    # Check for success or known benign errors
    # The "missing 'email' field" error is a benign ADK CLI warning when using Agent Identity
    benign_errors = [
        "service account info is missing 'email' field",
    ]

    deploy_failed = result.returncode != 0
    is_benign = any(err in (result.stdout + result.stderr) for err in benign_errors)

    if deploy_failed and not is_benign:
        print(f"   ❌ Deployment failed with exit code {result.returncode}")
        print()
        print("   Note: The Agent Engine instance was created but code deployment failed.")
        print(f"   You can retry with: export AGENT_ENGINE_ID={agent_engine_id}")
        sys.exit(1)
    elif deploy_failed and is_benign:
        print("   ⚠️  ADK CLI reported an error, but this is a known issue with Agent Identity.")
        print("   The deployment likely succeeded. Testing...")
        print()

except FileNotFoundError:
    print("   ❌ Error: 'adk' command not found")
    print("   Make sure google-adk is installed: pip install google-adk")
    sys.exit(1)

print()

# =============================================================================
# Verify Agent Identity
# =============================================================================

print("Phase 6: Verifying Agent Identity")

# agent_identity should already be set from Phase 4
# Only recompute if it wasn't set (e.g., Phase 4 failed)
if not agent_identity or agent_identity.startswith("<"):
    try:
        # First try to use effective_identity if it was captured
        if effective_identity:
            if effective_identity.startswith("principal://"):
                agent_identity = effective_identity
            else:
                agent_identity = f"principal://{effective_identity}"
        else:
            # Fallback: construct it ourselves
            # Get organization ID
            result = subprocess.run(
                ["gcloud", "organizations", "list", "--format=value(ID)", "--limit=1"],
                capture_output=True, text=True, timeout=30
            )
            org_id = result.stdout.strip()

            # Get project number
            result = subprocess.run(
                ["gcloud", "projects", "describe", PROJECT_ID, "--format=value(projectNumber)"],
                capture_output=True, text=True, timeout=30
            )
            project_number = result.stdout.strip()

            if org_id:
                agent_identity = f"principal://agents.global.org-{org_id}.system.id.goog/resources/aiplatform/projects/{project_number}/locations/{LOCATION}/reasoningEngines/{agent_engine_id}"
            else:
                # Use proj- format (observed in recent API responses)
                agent_identity = f"principal://agents.global.proj-{project_number}.system.id.goog/resources/aiplatform/projects/{project_number}/locations/{LOCATION}/reasoningEngines/{agent_engine_id}"

    except Exception as e:
        print(f"   ⚠️  Could not determine agent identity: {e}")
        agent_identity = "<check Google Cloud Console>"

    except Exception as e:
        print(f"   ⚠️  Could not determine agent identity: {e}")
        agent_identity = "<check Google Cloud Console>"

if agent_identity and not agent_identity.startswith("<"):
    print(f"   ✓ Agent Identity: {agent_identity}")
else:
    print("   ⚠️  Agent Identity could not be determined")

print()

# =============================================================================
# Output
# =============================================================================

print("=" * 70)
print("   ✅ Deployment Complete!")
print("=" * 70)
print()
print("   Save these values to set_env.sh:")
print()
print(f'   export AGENT_ENGINE_ID="{agent_engine_id}"')
if agent_identity and not agent_identity.startswith("<"):
    print(f'   export AGENT_IDENTITY="{agent_identity}"')
print()
print("   Then run:")
print()
print("   # Reload environment")
print("   source set_env.sh")
print()
print("   # Configure IAM for Agent Identity (see codelab)")
print("   # Grant BigQuery access to customer_service dataset only")
print()
print("   # Test the deployed agent")
print("   python scripts/test_deployed_agent.py")
print()
